export const Columns = [
  {
    prop: 'name',
    label: '名称',
    minWidth: 100,
    fixed: true,
    sortable: true,
  },
  {
    prop: 'description',
    label: '描述',
    minWidth: 100,
    sortable: true,
    fixed: true,
  },
  {
    prop: 'status',
    label: '状态',
    minWidth: 100,
    sortable: true,
    fixed: true,
  },
  {
    prop: 'readOnly',
    label: '只读',
    minWidth: 100,
    sortable: true,
    fixed: true,
  },
  {
    prop: 'generatorType',
    label: '代码生成器类型',
    minWidth: 100,
    sortable: true,
    fixed: true,
  },
  {
    prop: 'principal',
    label: '负责人',
    minWidth: 100,
    sortable: true,
    fixed: true,
  },
  {
    prop: 'sonarQubeAddress',
    label: '代码质量',
    minWidth: 100,
    sortable: true,
    fixed: true,
  },
  {
    prop: 'levelName',
    label: '级别',
    minWidth: 100,
    sortable: true,
    fixed: true,
  },
  {
    prop: 'createUser',
    label: '创建账号',
    minWidth: 100,
    sortable: true,
  },
  {
    prop: 'createUserName',
    label: '创建用户',
    minWidth: 100,
    sortable: true,
  },
  {
    prop: 'createsDate',
    label: '创建日期',
    minWidth: 100,
    sortable: true,
  },
  {
    prop: 'updateUser',
    label: '更新账号',
    minWidth: 100,
    sortable: true,
  },
  {
    prop: 'updateUserName',
    label: '更新用户',
    minWidth: 100,
    sortable: true,
  },
  {
    prop: 'updateDate',
    label: '更新日期',
    minWidth: 100,
    sortable: true,
  },
  {
    prop: 'version',
    label: '更新次数',
    minWidth: 100,
    sortable: true,
  },
  {
    prop: 'databaseIp',
    label: '数据库IP',
    minWidth: 100,
    sortable: true,
  },
  {
    prop: 'databasePort',
    label: '数据库端口',
    minWidth: 100,
    sortable: true,
  },
  {
    prop: 'databaseName',
    label: '数据库名称',
    minWidth: 100,
    sortable: true,
  },
  {
    prop: 'databaseUserName',
    label: '数据库用户',
    minWidth: 100,
    sortable: true,
  },
  {
    prop: 'databaseUserPassword',
    label: '数据库密码',
    minWidth: 100,
    sortable: true,
  },
  {
    prop: 'token',
    label: 'TOKEN',
    minWidth: 100,
    sortable: true,
  },
  {
    prop: 'assigned',
    label: '已分配用户',
    minWidth: 100,
    sortable: true,
  },
  {
    prop: 'freezeHours',
    label: '每日冻结时段',
    minWidth: 100,
    sortable: true,
  },
  {
    prop: 'canAccessMicroObjects',
    label: '开放微对象给项目',
    minWidth: 100,
    sortable: true,
  },
  {
    prop: 'canAccessMicroServices',
    label: '开放微服务给项目',
    minWidth: 100,
    sortable: true,
  },
  {
    prop: 'canAccessMicroModules',
    label: '开放微模块给项目',
    minWidth: 100,
    sortable: true,
  },
  {
    prop: 'openMicroObjectToProjects',
    label: '能访问微对象的项目',
    minWidth: 100,
    sortable: true,
  },
  {
    prop: 'openMicroServiceToProjects',
    label: '能访问微服务的项目',
    minWidth: 100,
    sortable: true,
  },
  {
    prop: 'openMicroModuleToProjects',
    label: '能访问微模块的项目',
    minWidth: 100,
    sortable: true,
  },
];
