export const Columns = [
  {
    prop: 'name',
    label: '名称',
    minWidth: 100,
    fixed: true,
    sortable: true,
  },
  {
    prop: 'account',
    label: '账号',
    minWidth: 100,
    sortable: true,
    fixed: true,
  },
  {
    prop: 'readonly',
    label: '只读',
    minWidth: 100,
    sortable: true,
    fixed: true,
  },
  {
    prop: 'email',
    label: '邮箱',
    minWidth: 100,
    sortable: true,
    fixed: true,
  },
  {
    prop: 'phone',
    label: '手机',
    minWidth: 100,
    sortable: true,
    fixed: true,
  },
  {
    prop: 'superAccount',
    label: '超级账号',
    minWidth: 100,
    sortable: true,
    fixed: true,
  },
  {
    prop: 'management',
    label: '管理权限',
    minWidth: 100,
    sortable: true,
    fixed: true,
  },
  {
    prop: 'enable',
    label: '是否启用',
    minWidth: 100,
    sortable: true,
    fixed: true,
  },
  {
    prop: 'epireDate',
    label: '过期时间',
    minWidth: 100,
    sortable: true,
  },
  {
    prop: 'createdProject',
    label: '已经创建项目',
    minWidth: 100,
    sortable: true,
  },
  {
    prop: 'AssignedProject',
    label: '已分配项目',
    minWidth: 100,
    sortable: true,
  },
  {
    prop: 'created',
    label: '创建时间',
    minWidth: 100,
    sortable: true,
  },
  {
    prop: 'updated',
    label: '更新时间',
    minWidth: 100,
    sortable: true,
  },
  {
    prop: 'team',
    label: '团队',
    minWidth: 100,
    sortable: true,
  },
];
