import getConfig from '.';

const {
  COS_CONFIG_BUCKET,
  COS_CONFIG_REGION,
  COS_CONFIG_SECRETID,
  COS_CONFIG_SECRETKEY,
  COS_CONFIG_STORAGECLASS,
  COS_CONFIG_ENDPOINT,
} = getConfig();

// 腾讯云对象存储cos设置
export default  {
  Bucket: COS_CONFIG_BUCKET,
  Region: COS_CONFIG_REGION,
  SecretId: COS_CONFIG_SECRETID,
  SecretKey: COS_CONFIG_SECRETKEY,
  StorageClass: COS_CONFIG_STORAGECLASS,
  Endpoint: COS_CONFIG_ENDPOINT,
};
